buckets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^s3/(?P<bucket>[\w\-\.]+)/(?P<path>.*)/$', 'buckets.s3.views.list', name='s3_path'),
    url(r'^s3/(?P<bucket>[\w\-\.]+)/$', 'buckets.s3.views.list', name='s3_bucket'),
    url(r'^s3/$', 'buckets.s3.views.bucket_list', name='s3_bucket_list'),
    url(r'^$', RedirectView.as_view(url='/s3/')),
    url(r'^', include('googleauth.urls')),
)

urls.py
from django.conf.urls import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^s3/(?P<bucket>[\w\-\.]+)/(?P<path>.*)/$', 'buckets.s3.views.list', name='s3_path'),
    url(r'^s3/(?P<bucket>[\w\-\.]+)/$', 'buckets.s3.views.list', name='s3_bucket'),
    url(r'^s3/$', 'buckets.s3.views.bucket_list', name='s3_bucket_list'),
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url': '/s3/'}),
    url(r'^', include('googleauth.urls')),
    url(r'^', include('mediasync.urls')),
)

buckets/s3/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

class BucketPermission(models.Model):
    user = models.ForeignKey(User, related_name='s3_permissions')
    bucket = models.CharField(max_length=255)
    full_access = models.BooleanField(default=False)
    
    class Meta:
        unique_together = ('user','bucket')
    
    def __unicode__(self):
        return u"%s %s" % (self.user.username, self.bucket)

class PathPermission(models.Model):
    bucket_permission = models.ForeignKey(BucketPermission, related_name="paths")
    value = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('value',)
    
    def __unicode__(self):
        return self.value
    
    def save(self):
        self.value = self.value.strip('/')
        super(PathPermission, self).save()

buckets/s3/views.py
import json
import mimetypes
import re
from base64 import b64decode
from boto.s3.key import Key
from boto.s3.prefix import Prefix
from buckets.s3.models import BucketPermission
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render


def load_permissions(user):
    """ Load permissions from database into data structure.
    """

    perms = {}  # dict to hold permissions

    # iterate over all bucket permissions for the user
    bucket_perms = BucketPermission.objects.filter(user=user)
    for bp in bucket_perms:

        # dict to hold bucket-specific permissions
        # full_access == True gives read/write access to entire bucket
        perms[bp.bucket] = {
            'tree': {},
            'full_access': bp.full_access,
        }

        # iterate over the user/bucket path permissions
        for pp in bp.paths.all():

            node = perms[bp.bucket]['tree']

            # iterate over parts of the permission path
            for d in pp.value.split('/'):
                # add current part to tree
                if d not in node:
                    node[d] = {}
                node = node[d]

            # add * at end of path to indicate end of permission
            node['*'] = True

    return perms


def has_permission(user, perms, bucket, path=None):
    """ Test to see if a user has permission to access a bucket
        and or an associate path on the bucket.
    """

    # superusers have read/write access to everything
    if user.is_superuser:
        return (True, True)

    # no access if bucket is not in list of permissions
    if bucket not in perms:
        return (False, False)

    # If path is not specified, allow read_access since we've already
    # established that the user has bucket permission. Allow write
    # access only if user has full_access permission set.
    if not path or perms[bucket]['full_access']:
        return (True, perms[bucket]['full_access'])

    # make path safe and standardized
    path = ('' if path is None else path).strip('/')

    # get bucket's permission tree
    node = perms[bucket]['tree']

    # iterate over parts of current path
    for d in path.split('/'):

        # test to see if part is in permission tree
        node = node.get(d, None)

        if node is None:
            # no read/write access if current path is not in tree
            return (False, False)

        if '*' in node:
            # allow read/write if we've reached a full permission path
            return (True, True)

    # If we've gotten this far then we have permission on a subdirectory
    # of the current directory. Allow reads but no writes.
    return (True, False)


def load_buckets(request):
    if request.user.is_superuser:
        buckets = [b.name for b in request.s3.get_all_buckets()]
    else:
        buckets = [p.bucket for p in request.user.s3_permissions.all()]
    return buckets


@login_required
def bucket_list(request):
    buckets = load_buckets(request)
    request.session['buckets'] = buckets
    request.session['perms'] = load_permissions(request.user)
    return render(request, 'list_buckets.html', {'buckets': buckets})


@login_required
def list(request, bucket, path=None):

    perms = request.session['perms']

    (can_read, can_write) = has_permission(request.user, perms, bucket, path)
    if not can_read:
        return HttpResponseForbidden('%s does not have access to %s/%s' % (request.user.email, bucket, path or ''))

    if 'buckets' not in request.session:
        request.session['buckets'] = load_buckets(request)

    path = (('' if path is None else path) + '/').lstrip('/')
    path_parts = path.strip('/').split('/')

    if request.method == 'POST':
        return upload(
                request,
                bucket,
                path + request.POST.get('filename'),
                b64decode(request.POST.get('data')))

    b = request.s3.get_bucket(bucket)

    pl = len(path)

    files = []
    directories = []

    for l in b.list(path or '', delimiter='/'):
        if l.name != path:
            f = {'name': l.name[pl:], 'path': l.name.strip('/')}
            if isinstance(l, Prefix):
                (can_subdir_read, can_subdir_write) = has_permission(request.user, perms, bucket, l.name)
                if can_subdir_read:
                    f['can_read'] = can_subdir_read
                    f['can_write'] = can_subdir_write
                    directories.append(f)
            elif can_write:
                f['mimetype'] = mimetypes.guess_type(f['name'])[0]
                files.append(f)

    path_list = []
    tmp_path = ''
    for p in path_parts:
        tmp_path = ('%s/%s' % (tmp_path, p)).strip('/')
        path_list.append({
            'name': p,
            'path': tmp_path.strip('/'),
        })

    params = {
        'buckets': request.session['buckets'],
        'bucket': bucket,
        'path': path,
        'path_list': path_list,
        'directories': directories,
        'can_read': can_read,
        'can_write': can_write,
        'files': files,
        'parent': path_parts[-2] if len(path_parts) > 1 else bucket,
        'parent_path': "/".join(path_parts[:-1]),
        'pwd': path_parts[-1],
    }

    if 'json' in request.GET:
        return HttpResponse(json.dumps(params), mimetype='application/json')
    elif 'partial' in request.GET:
        return render(request, 'list.html', params)
    else:
        return render(request, 'list_bucket.html', params)


def upload(request, bucket, key, data):

    if not key or key.endswith('/'):
        raise ValueError('key required for upload')

    perms = request.session['perms']
    (can_read, can_write) = has_permission(request.user, perms, bucket, key)

    if not can_write:
        return HttpResponseForbidden('%s does not have access to %s/%s' % (request.user.email, bucket, key or ''))

    b = request.s3.get_bucket(bucket)
    k = Key(bucket=b, name=key)

    if k.exists() and 'force' not in request.GET:
        raise HttpResponseForbidden('write failed: file exists')

    headers = {
        "x-amz-acl": "public-read",
        "Content-Length": len(data),
    }

    ct = mimetypes.guess_type(key)[0]
    if ct is not None:
        headers["Content-Type"] = ct

    k.set_contents_from_string(data, headers=headers)
    k.set_metadata('uploaded-by', request.user.email)

    if request.is_ajax():
        return HttpResponse('{}')
    else:
        return redirect('/' + '/'.join(path.split('/')[:-1]))

buckets/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>buckets</title>
		<link rel="stylesheet" href="/static/styles/reset.css">
		<link rel="stylesheet" href="/static/styles/text.css">
		<link rel="stylesheet" href="/static/styles/960.css">
		<link rel="stylesheet" href="/static/styles/screen.css">
		<link rel="stylesheet" href="/static/styles/jquery.fancybox-1.3.1.css">
	</head>
	<body class="{% block bodyclass %}{% endblock %}">
		<div id="container">
			<header>
				{% if user.is_authenticated %}
					<div id="hey">
						<p>Hey, <span class="email">{{ user.email }}</span>, <a href="/logout/">logout</a> when you are done.</p>
					</div>
				{% endif %}
				<hgroup>
					<h1>buckets</h1>
					<h2>Amazon S3 content manager</h2>
				</hgroup>
				{% block nav %}{% endblock %}
			</header>
			<div id="content">
				{% block content %}{% endblock %}
				<div style="clear: both;"></div>
			</div>
			<div id="overlays">
				<div id="actions-box">
					<p>awesome actions!</p>
				</div>
			</div>
		</div>
		<script src="/static/scripts/jquery-1.4.2.min.js"></script>
		<script src="/static/scripts/jquery.mousewheel-3.0.2.pack.js"></script>
		<script src="/static/scripts/jquery.fancybox-1.3.1.pack.js"></script>
		<script src="/static/scripts/buckets.js"></script>
	</body>
</html>

buckets/templates/list.html
<ol id="directories">
    {% if can_write %}
    	<li class="new-directory" data-bucket="{{ bucket }}" data-keyprefix="/{{ path }}" data-canwrite="True">
    		Drop here to create a new directory.
    	</li>
	{% endif %}
	{% for d in directories %}
		<li class="directory" data-bucket="{{ bucket }}" data-keyprefix="/{{ d.path }}/" data-canwrite="{{ d.can_write }}">
			<a href="{% url 's3_path' bucket d.path %}" class="name">{{ d.name }}</a>
			<a href="#actions-box" class="actions">actions</a>
		</li>
	{% endfor %}
</ol>
<ol id="files" data-bucket="{{ bucket }}" data-keyprefix="/{{ path }}" data-canwrite="{{ can_write }}">
	{% if files %}
		{% for f in files %}
			<li class="file{% if f.mimetype %} {{ f.mimetype }}{% endif %}">
				<a href="http://{{ bucket }}.s3.amazonaws.com/{{ f.path }}" class="name">{{ f.name }}</a>
				<a href="#actions-box" class="actions">actions</a>
			</li>
		{% endfor %}
	{% else %}
	    {% if can_write %}
		    <li class="no-files">Drop a file here to upload.</li>
		{% endif %}
	{% endif %}
</ol>
<form action="." id="upload-form">
	{% csrf_token %}
</form>

buckets/templates/list_bucket.html
{% extends "base.html" %}

{% block nav %}
	<nav>
		<ol id="pwd" class="cleared">
			<li class="organization"><a href="/s3/">Buckets</a></li>
			<li class="bucket"><a href="{% url 's3_bucket' bucket %}">{{ bucket }}</a></li>
			{% if path_list %}
				{% for p in path_list %}
					{% if forloop.last %}
						<li class="current">{{ p.name }}</li>
					{% else %}
						<li class="path"><a href="{% url 's3_path' bucket p.path %}">{{ p.name }}</a></li>
					{% endif %}
				{% endfor %}
			{% endif %}
		</ol>
	</nav>
{% endblock %}

{% block content %}
	<div id="browser">
		<header>
			{% if path %}
				<a href="/s3/{{ bucket }}{% if parent_path %}/{{ parent_path }}{% endif %}/" class="back">return to <em>{{ parent }}</em></a>
			{% else %}
				<a href="{% url 's3_bucket_list' %}" class="back">return to bucket listing</a>
			{% endif %}
			<h2>{% if pwd %}{{ pwd }}{% else %}{{ bucket }}{% endif %}</h2>
		</header>
		<nav id="ls">
			{% include "list.html" %}
		</nav>
	</div>
	<div id="options">
		<form action="." method="post" id="bucket_switcher">
			<label for="id_bucket">switch bucket to</label>
			<select name="bucket" id="id_bucket">
				<option value=""></option>
				{% for b in buckets %}
					<option value="{{ b }}"{% if b == bucket %} selected{% endif %}>{{ b }}</option>
				{% endfor %}
			</select>
			<input type="submit" value="switch bucket">
		</form>
		<ul id="uploads"></ul>
	</div>
{% endblock %}

buckets/templates/list_buckets.html
{% extends "base.html" %}

{% block bodyclass %}buckets{% endblock %}

{% block content %}
	<div id="browser">
		<nav id="ls">
			<ol id="directories">
				{% for b in buckets %}
					<li class="directory" data-bucket="{{ b }}" data-keyprefix="/">
						<a href="{% url 's3_bucket' b %}" class="name">{{ b }}</a>
					</li>
				{% endfor %}
			</ol>
		</nav>
	</div>
{% endblock %}